### ISSUE TITLE
private/deleted repo makes git fetch --all require credentials

### ISSUE THREAD

**Issue by diracdeltas** [diracdeltas/tweets#12]
https://github.com/jayaddison/tweets is private so it makes git prompt for username/password when running `git fetch --all` with that repo as one of the remotes

**Comment by diracdeltas** [comment]
cc @jayaddison

**Comment by diracdeltas** [comment]
@nikolaydubina your repo also seems to be causing this issue jfyi

**Comment by nikolaydubina** [comment]
hey, I actually deleted my repo.. 🙇🏻‍♂️

**Comment by guites** [comment]
yeah i was wondering if we could make a script to automatically remove invalid remotes

their http status goes to 404, eg

```
> curl -I https://github.com/nikolaydubina/tweets/
HTTP/2 404
server: GitHub.com
date: Mon, 07 Nov 2022 11:18:19 GMT
content-type: text/html; charset=utf-8
```

**Comment by jayaddison** [comment]
Ah, apologies for breaking the jankyverse :whale: 

`GIT_TERMINAL_PROMPT=0` could be one way to resolve this? (`git` won't attempt to prompt for credentials in that case)
