### ISSUE TITLE
GAnarchy support

### ISSUE THREAD

**Issue by SoniEx2** [diracdeltas/tweets#2]
we already have a front-end, just make a commit like so:

```text
[Project] Tweets

Tweets.
```

and it'll show up on https://ganarchy.github.io/

**Comment by diracdeltas** [comment]
wow didnt know about this

**Comment by SoniEx2** [comment]
close enough XD https://ganarchy.github.io/project/1cf233f31ba84dba2b7cbcde6c160b0fdf4141ac/
