### ISSUE TITLE
Post as gh_pages

### ISSUE THREAD

**Issue by gbraad** [diracdeltas/tweets#4]
... with an RSS feed. This way this is also more publicly accessible with standard tools.

**Comment by donaldguy** [comment]
<img width="301" alt="image" src="https://user-images.githubusercontent.com/43136/200207119-5feb92c9-af60-4555-a5f8-e7fff37eda68.png">

#WONTFIX

**Comment by donaldguy** [comment]
See also:

https://twitter.com/bcrypt/status/1588980381550010368

<img width="549" alt="image" src="https://user-images.githubusercontent.com/43136/200207174-df7f74e0-e58c-4e8d-bc40-2c2b86fb123b.png">

**Comment by guites** [comment]
you could technically fork this and front end away. they cant stop you

**Comment by gbraad** [comment]
#sarcasm
